# Generated by Django 3.2 on 2021-06-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youconv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='file_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
